# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main
- dpauth-ui/*

pool:
  name: 'local-self-hosted'

steps:
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '"$(System.DefaultWorkingDirectory)/dpauth-ui/"'
    customCommand: 'install'
- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '"$(System.DefaultWorkingDirectory)/dpauth-ui"'
    customCommand: 'run build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'dpauth-ui'
    publishLocation: 'Container'